<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_TestFunction" Id="{202e3aee-003d-4ef2-8f26-aaa665cfe0a3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestFunction
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TestFunction">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>